project:
  type: website

website:
  title: "Misha Reiss"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: Projects
    right:
      - icon: github
        text: Website Source Code
        url: https://github.com/mishareiss9/personal-website
      - text: Github Profile
        url: https://github.com/mishareiss9

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

